apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bmux
resources:
  - website.yaml
images:
  - name: registry.tonisives.com/bmux-website
    digest: sha256:6a8380f1a9c40b23b7e8fca12c0803d3da00710237def43c4595e887aec40475
