apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmux-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bmux-website
  template:
    metadata:
      labels:
        app: bmux-website
    spec:
      imagePullSecrets:
        - name: tonisives-registry-secret
      containers:
        - name: website
          image: registry.tonisives.com/bmux-website
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: bmux-website
spec:
  selector:
    app: bmux-website
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bmux-website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts: [bmux.tonis.dev]
      secretName: bmux-tonis-dev-tls
  rules:
    - host: bmux.tonis.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bmux-website
                port:
                  number: 80
